### ISSUE TITLE
Left Nav not working - quotes

### ISSUE THREAD

**Issue by DuncanChittick** [imbercal/imbercal-issues#17]
After selecting ' Generate new quote' left nav stops working

![screen shot 2015-04-24 at 20 55 25](https://cloud.githubusercontent.com/assets/11769538/7327358/5d245cdc-eac4-11e4-97d5-7a9f4dba2e74.png)

**Comment by DuncanChittick** [comment]
This error persists throughout including generate invoice

**Comment by imbercal** [comment]
This has been fixed on the quotes page, although quotes page itself needs some formatting. Invoice page treated separately.
