### ISSUE TITLE
Content Box Alignment Issue

### ISSUE THREAD

**Issue by DuncanChittick** [imbercal/imbercal-issues#41]
http://dev.imbercal.com/sales/receipts

Content box 1 is aligned center - this would look better left as per box 2.

**Comment by DuncanChittick** [comment]
![screen shot 2015-05-10 at 22 09 29](https://cloud.githubusercontent.com/assets/11769538/7556262/5c92ea82-f761-11e4-8306-dd45a3e8d8f0.png)

**Comment by DuncanChittick** [comment]
http://dev.imbercal.com/purchases/payments

Same here

**Comment by imbercal** [comment]
closing for now until we come up with a better solution - it works for now!
