### ISSUE TITLE
STYLING - Dashboard Notifications

### ISSUE THREAD

**Issue by DuncanChittick** [imbercal/imbercal-issues#51]
http://dev.imbercal.com/index.php

Your changes saved notification need a styled notification box. 

![screen shot 2015-05-10 at 22 27 50](https://cloud.githubusercontent.com/assets/11769538/7556317/e79c9ce8-f763-11e4-9760-9be2a4974eff.png)

**Comment by imbercal** [comment]
fixed in previous commit
