### ISSUE TITLE
Dead link ' Forgot account number?' on Login page

### ISSUE THREAD

**Issue by janaredd** [imbercal/imbercal-issues#60]
Nothing is happening on click of ' Forgot account number?' link on the login page

Expected: User should be able to navigate to the ' Forgot account number?' form once after click on the link on login page
![forgot_ac](https://cloud.githubusercontent.com/assets/8011533/7616130/e3f5cbb0-f9bf-11e4-99fc-281bee76cad9.jpg)

**Comment by imbercal** [comment]
Closed by commit #3903c54
