### ISSUE TITLE
Incorrect Date format is showing on the page

### ISSUE THREAD

**Issue by janaredd** [imbercal/imbercal-issues#74]
1. Go to this page: http://dev.imbercal.com/bank/accountStatement/bank/109543
Issue 1: Notice that the date format is showing as 00/00/0000 -00/00/0000 instead DD/MM/YYYY - DD/MM/YYYY
Issue 2: The column name in the report is showing as ' Ref' -It got confused what is this mean of?
instead provide a full word
Issue 3: Description text should not show in bold 'Balance bought forwards',because header and description text both should not showing bold
Issue 4: Choose the option ' Current' from Accounting Period: drop down and notice that Month From: & Month To: is showing March 2016 - a future date instead of present date
Issue 5: Section heading should be corrected -
Current in the application : Bank transactions 
Expected : Bank Transactions

![dateformate](https://cloud.githubusercontent.com/assets/8011533/7637739/b472ae5c-fa8d-11e4-9241-e4e78d95563d.jpg)

**Comment by imbercal** [comment]
This is caused as a result of account not being set up correctly - due to lack of validation on the earlier pages - fixed via another update.
