### ISSUE TITLE
Section name is not meaningful and be changed?

### ISSUE THREAD

**Issue by janaredd** [imbercal/imbercal-issues#75]
1. Go to this page : http://dev.imbercal.com/bank/statements
Issue : Notice the section name is showing as  " Account Name' - which doesn't make sense

Expected: It would be good if it is changed to ' Account Type' 

![accountname](https://cloud.githubusercontent.com/assets/8011533/7637807/27ea4e9e-fa8e-11e4-920d-f0253c6aa466.jpg)

**Comment by imbercal** [comment]
Closed - no issue here, it should be account name as further accounts may be added so eg Bank Current Account, HSBC Account, etc
