### ISSUE TITLE
Functionality is broken- Nothing is happening by click on Submit button

### ISSUE THREAD

**Issue by janaredd** [imbercal/imbercal-issues#77]
1. Go to this page http://dev.imbercal.com/bank/transfer
2. Choose ' Cash Account ' for Bank account the transfer is being made from:
3. Choose ' Company Credit Card' for Bank account the transfer is being made to:
4. Select tomorrows date for Date of the transfer: field
5. Click on Submit button
Notice that nothing is happening and no clue to the use what is happening.

Issue 2: Date of the transfer: field is accepting past date and it should not allow users to choose old dates and it should only allow present and feature dates.

![submit_notworking](https://cloud.githubusercontent.com/assets/8011533/7638147/6416b680-fa90-11e4-8f62-f8ee8029493d.jpg)

**Comment by janaredd** [comment]
Issue 2: Also Amount being transferred: is accepting characters
Issue 3: Reset button functionality is not working

**Comment by imbercal** [comment]
Issues fixed in the next commit. Please be aware that dates in the past are acceptable.
