### ISSUE TITLE
Other company name CloudBooks? is showing in the help instead 'Imbercal'

### ISSUE THREAD

**Issue by janaredd** [imbercal/imbercal-issues#83]
Why it is showing CloudBooks? on this page : http://dev.imbercal.com/help

Under this section: by most popular

    How do I change my password?
    How do I change my company name on CloudBooks?
    What is this 'API' thing I keep hearing about?
    How can I delete an erronous entry?
    Why don't the headline figures displayed on my homepage agree to my trial balance?
    How do I delete a transaction?
    Why can't I delete certain transactions?
    What are Journals?
    How can I tell how much I owe to my suppliers?
    How do I get emails to customers to come from my email address, not CloudBooks?
    How do I raise an invoice to a customer?
    How safe is my information?
    How do I give another person access to my CloudBooks account?
    What are the different levels of users?
    How do I run my VAT Return?
    How do I submit my VAT Return directly to HMRC through the CloudBooks system?

Expected: It should not show this CloudBooks and it should show 'Imbercal'
Note: I don't know whether this is expected or not..please confirm.

**Comment by imbercal** [comment]
closed via updates to the database to correct this
