### ISSUE TITLE
Security Issue : previous accessed pages should not accessible after log out i.e. Sign out and then press the Back button to access the page accessed before.

### ISSUE THREAD

**Issue by janaredd** [imbercal/imbercal-issues#97]
Previously accessed pages should not accessible after log out i.e. Sign out and then press the Back button to access the page accessed before.

This is reproducible in the application.Please take care.

**Comment by imbercal** [comment]
I've been unable to recreate this issue. I have made some changes to increase security - please advise if still replicatable.
